### PR TITLE
All the interesting commits from the winston-rsyslog fork network

### PR DESCRIPTION
**Pull request by markstos**
Hello,

Thanks for taking the lead in uploading a forked winston-rsyslog that continues the maintenance. 

Today I've taken a further step and reviewed every un-merged commit in the network. I weeded out the duplicates merged or patched the worthwhile patches into a single branch with a relatively clean history. 

I also added "CHANGELOG.md" to show the differences between "winston-rsyslog2" and the original as well as to provide a clear summary of the commits I'm proposing.

I propose this branch be merged into `winston-rsyslog2` if it looks good to you. Note that for a release, the CHANGELOG.md should be updated with the release version and date. 

I think a version bump could also be in order to at least `0.1.0` if not further to note there have been several additions since the last release. 

Thanks to the other forkers who made improvements and published them.

### CODE REVIEW

**Comment by markstos** [comment]
@verkholantsev  Just a heads-up: I've reviewed, merged, cherry-picked or patched several winston-rsyslog patches to propose to be merged into the fork that's `winston-rsyslog2`. Several updates from you are in the batch-- Thanks!  Your review and comments on the result are welcome as well. 

@imsky It would also be nice if you could go into 'settings' for your fork and enable "Issues" so further feedback can be reported instead of the original inactive branch.

**Comment by imsky** [comment]
Thanks very much, I'll review this and merge ASAP.

Issues have been enabled.

**Comment by imsky** [comment]
Looks good, I'll keep adding changes to clean up.

Thanks for this.

**Comment by verkholantsev** [comment]
So is `winston-rsyslog` now deprecated due to `winston-rsyslog2`?

**Pull request merged**
